server:
  port: 9999

spring:
  application:
    name: config-repo

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/aouniR/healthcare-system-config"
          searchPaths:
            - "config-repo"

authentication-service:
  url: http://authentication-service:8081
  credentials:
    username: auth_user
    password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S
  application-title: Authentication Service

user-service:
  url: http://user-service:8082
  database:
    url: jdbc:postgresql://user-service-db:5432/userdb
    username: user_service
    password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S

metamodel-service:
  url: http://metamodel-service:8083
  database:
    url: jdbc:postgresql://metamodel-service-db:5432/metamodeldb
    username: metamodel_service
    password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S

medical-record-service:
  url: http://medical-record-service:8084
  database:
    url: jdbc:postgresql://medical-record-service-db:5432/medicalrecorddb
    username: medical_record_service
    password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S

medical-component-service:
  url: http://medical-component-service:8085
  database:
    url: jdbc:postgresql://medical-component-service-db:5432/medicalcomponentdb
    username: medical_component_service
    password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S

notification-service:
  url: http://notification-service:8086
  database:
    url: jdbc:postgresql://notification-service-db:5432/notificationdb
    username: notification_service
    password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

api-gateway:
  url: http://api-gateway:8080
  description: API Gateway for routing requests to microservices
  routes:
    - id: authentication-service-route
      uri: http://authentication-service:8081
      predicates:
        - Path=api/v1/auth/**
    - id: user-service-route
      uri: http://user-service:8082
      predicates:
        - Path=api/v1/user/**
    - id: metamodel-service-route
      uri: http://metamodel-service:8083
      predicates:
        - Path=api/v1/metamodel/**
    - id: medical-record-service-route
      uri: http://medical-record-service:8084
      predicates:
        - Path=api/v1/medical-record/**
    - id: medical-component-service-route
      uri: http://medical-component-service:8085
      predicates:
        - Path=api/v1/medical-component/**
    - id: notification-service-route
      uri: http://notification-service:8086
      predicates:
        - Path=api/v1/notification/**

application:
  description: Development Environment for Healthcare-system with Spring-boot microservices architecture
  license: Dev API Licence
  version: 1.0
