server:
  port: 8084

spring:
  application:
    name: medicalrecord-service
    application-title: MedicalRecord Service
    application-description: The medicalrecord service for Healthcare-system with Spring-boot microservices architecture
    application-version: 1.0
    application-license: Dev API Licence

  data:
    mongodb:
      uri: mongodb://medicalrecord-user:1234@medicalrecord-service-db:27018/medicalrecorddb
  
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_SERVER_URL:http://eureka-service:8761/eureka/}
    instance:
      prefer-ip-address: true

  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: medical-record-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.healthcare.medicalrecord_service.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
    topic:
      medicalRecord-events: medicalRecord-events-topic
      metaModelProducer-events: metaModelListener-events-topic
      metaModelListener-events: metaModelListener-events-topic
      medicalMonitoring-events: medicalMonitoring-events-topic
      medicalProcedure-events: medicalProcedure-events-topic
jwt:
  secret-key: 8bTjzD5Yl4I9jQ8M7G3wD1k+S3ZbqC+7e8A1aPqF2B4W=
  expiration-time: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG     
