server:
  port: 8082

spring:
  application:
    name: user-service
    application-title: User Service
    application-description: The user service for Healthcare-system with Spring-boot microservices architecture
    application-version: 1.0
    application-license: Dev API Licence

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user_service
    password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  
    properties:
      hibernate:
        format_sql: true  

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    clean-disabled: false

  cloud:
    config:
      uri: http://localhost:8888
      failFast: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

  kafka:
    bootstrap-servers: brocker:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: "*"
    topic:
      user-events: user-events-topic
jwt:
  secret-key: 8bTjzD5Yl4I9jQ8M7G3wD1k+S3ZbqC+7e8A1aPqF2B4W=
  expiration-time: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG
        
