server:
  port: 8082

spring:
  application:
    name: user-service
    url: http://user-service:8082
    credentials:
      username: user_service
      password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S
    title: User Service
    description: the user service for Healthcare-system with Spring-boot microservices architecture
    version: 1.0
    license: Dev API Licence
    
  cloud:
    config:
      uri: http://localhost:8888
      failFast: true
