server:
  port: 8081

spring:
  application:
    name: authentication-service
    url: http://authentication-service:8081
    credentials:
      username: auth_user
      password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S
    title: Authentication Service
    description: The authentication service for Healthcare-system with Spring Boot microservices architecture
    version: 1.0
    license: Dev API Licence
    
  cloud:
    config:
      uri: http://localhost:8888
      failFast: true
