server:
  port: 8081

spring:
  application:
    name: authentication-service
    url: http://authentication-service:8081
    credentials:
      username: auth_user
      password: E8C7D%j9@#G5Z!2u8q&1E8kLx9m^Wb7S
    application-title: Authentication Service
    application-description: The authentication service for Healthcare-system with Spring Boot microservices architecture
    application-version: 1.0
    application-license: Dev API Licence
    
  cloud:
    config:
      uri: http://localhost:8888
      failFast: true

jwt:
  secret-key: "8bTjzD5Yl4I9jQ8M7G3wD1k+S3ZbqC+7e8A1aPqF2B4W="